---

- name: Update the database
  hosts: apiservers
  become: yes

  vars:
    project_name: xassida
    data_dir: /home/{{ ansible_user }}/{{ project_name }}/data

  tasks:
     - name: Pull the changes from github
       command: git pull origin main
       args:
         chdir: "{{ data_dir }}"
       tags:
        - code

     - name: Make update_db.sh executable
       file:
         path: "{{ data_dir }}/update_db.sh"
         mode: u+x

     - name: Parse and Insert the xassida to database
       command: ./update_db.sh
       args:
         chdir: "{{ data_dir }}"