name: Test newly added or modifed xassida files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # change to appropriate version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get file changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Run Python parse_xassida script on changes
        if: ${{ steps.file_changes.outputs.files }}
        run: |
          matched_files=$(echo '${{ steps.file_changes.outputs.files }}')
          files=$(echo "$matched_files" | jq -r '.[]')
          processed=()
          for file in ${files[@]}; do
            if [[ $file == xassidas/**/*.txt ]]; then
              name=$(basename $file | cut -f 1 -d '.')
              if [[ " ${processed[@]} " =~ " $name " ]]; then
                echo "Skipping duplicate xassida $name"
              else
                if python parse_xassida.py -x "$name" && python parse_translations.py -x "$name"; then
                  echo "Processed xassida $name"
                  processed+=("$name")
                else
                  echo "Failed to process xassida $name"
                  exit 1
                fi
              fi
            fi
          done
