name: Update the database
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ansbile playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: update_db.yml
          directory: .ansible/playbooks/
          key: '${{ secrets.SECRET_SSH_KEY }}'
          inventory: |
            [apiservers]
            server1 ansible_host=${{ secrets.HOST }} ansible_user=${{ secrets.HOST_USER }}
          options: |
            --extra-vars xassidas=${{ env.XASSIDAS }}
            --user debian
            --ssh-extra-args "-o StrictHostKeyChecking=no"
            --verbose